### ISSUE TITLE
Process fails as soon as Powershell opens

### ISSUE THREAD

**Issue by Chill456** [notthebee/ytdl-explorer#7]
Hi,

I have Windows 10 Home 64 bit, and Powershell (version 5.1.19041.1) closes before anything happens.  I have done the following:

1) Installed Python for Windows 10 Home  - python-3.11.5-amd64.exe.
2) Followed all steps in the README.md, including installing youtube-dl and ffmpeg as an administrator with PowerShell. No errors occurred during installs.
3) I associated "RegFileGenerator.py" manually with "C:\Users\Chill456\AppData\Local\Programs\Python\Python311\python.exe"
4) Rebooted, in case the PY association needed that to happen.
5) Copied the link to a 1080p video of my own on YouTube.
6) Right clicked on the folder to receive the download (C:\TEMP\YTDL), and selected "yt-dlt", then "Download video H.264", and "1080p".
7) Powershell appears for half a second, and then closes.
8) I tried other resolutions, and the other video option DNxHR 25FPS.  Same result.

Best Regards,
Chill456

**Comment by tievex** [comment]
thats cuz u use yt-dl and not yt-dlp https://github.com/yt-dlp/yt-dlp#installation

**Comment by Chill456** [comment]
> thats cuz u use yt-dl and not yt-dlp https://github.com/yt-dlp/yt-dlp#installation

Thanks very much for your reply.  - I find that "yt_dlp.exe" (without ytdl-explorer) is easier for me to operate.  It works well, so I'm closing this issue.

**Comment by Chill456** [comment]
This issue is closed.
